name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README**'
      - 'LICENSE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README**'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install packages
        run: sudo apt-get update ; sudo apt-get install -y cmake gcc-12 libjansson-dev

      - name: Build ctl
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          build-type: Debug
