name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README**'
      - 'LICENSE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README**'
      - 'LICENSE'

jobs:
  build:
    name: Build and install
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-20.04, ubuntu-22.04 ]
    steps:
      - name: Install build requirements
        run: sudo apt-get update ; sudo apt-get install -y cmake gcc pkg-config libjansson-dev

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Intree build
        run: rm -rf build ; cmake -B build

      - name: Build Intree
        run: cmake --build build

      - name: Configure Static build
        run: rm -rf build ; cmake -B build -DCTL_LINK_TYPE=Static

      - name: Build and install Static
        run: cd build && make && sudo make install && sudo make uninstall

      - name: Configure Shared build
        run: rm -rf build ; cmake -B build -DCTL_LINK_TYPE=Shared -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release

      - name: Build and install Shared
        run: cd build && make && sudo make install && sudo make uninstall
  deploy:
    name: Deply to rocky9test1
    runs-on: rocky9test1
    steps:
      -name: First step
       run: touch file.txt
